# Generated by Django 3.1 on 2020-09-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20200903_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
