# Generated by Django 3.1 on 2020-09-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='test@test.com.ua', max_length=255, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='+380673322980', max_length=20, verbose_name='Номер телефона'),
        ),
    ]
