# Generated by Django 3.1 on 2020-09-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.TextField(blank=True, null=True, verbose_name='TEST'),
        ),
    ]
