# Generated by Django 3.1 on 2020-09-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20200908_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_birth',
            new_name='test_field',
        ),
    ]
