# Generated by Django 3.1 on 2020-09-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20200908_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='test_field',
            field=models.CharField(max_length=255, verbose_name='TEST'),
        ),
    ]
