# Generated by Django 3.1 on 2020-09-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20200908_1244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
