# Generated by Django 3.1 on 2020-09-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
