# Generated by Django 3.1 on 2020-09-09 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounttt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileee',
            name='test_field',
        ),
        migrations.AddField(
            model_name='profileee',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='profileee',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Номер телефона', max_length=31),
        ),
        migrations.AddField(
            model_name='profileee',
            name='tg_id',
            field=models.CharField(blank=True, default='1234567', max_length=15, null=True, verbose_name='Телеграмм ID'),
        ),
        migrations.AlterField(
            model_name='profileee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
