# Generated by Django 3.1 on 2020-09-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounttt', '0002_auto_20200909_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileee',
            name='first_name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profileee',
            name='last_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Фамилия'),
        ),
    ]
